### ISSUE TITLE
Image and re-size text

### ISSUE THREAD

**Issue by harshsinghcs** [harshsinghcs/Animated-text-01#1]
Change the image, re-size the text & change the font style to look good.

font size like that👇👇

![animated Hii](https://github.com/harshsinghcs/Animated-text-01/assets/115187902/797eca41-649e-477f-a2b4-fab508eb5f44)

**Comment by azro1** [comment]
hi Harsh i would like to make a change as my first contribution please assign me thanks

**Comment by harshsinghcs** [comment]
Hello Simon, I'm reviewing your pull request.
due to some issue, I'm unable to merge please send PR once again.
thankyou

**Comment by azro1** [comment]
thank you Harsh, of course will send again 👍

**Comment by azro1** [comment]
thank you Harsh, of course will send again 👍

**Comment by harshsinghcs** [comment]
All requirements of this issue are full.
